### ISSUE TITLE
Windows 2008R2 Platform

### ISSUE THREAD

**Issue by jrmash** [customink/fauxhai#181]
I am encountering the following issue when using the Windows 2008R2 platform:

```
JSON::ParserError:
       757: unexpected token at '??{'
     # /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:56:in `block in fauxhai_data'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:77:in `call'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:77:in `fauxhai_data'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:26:in `initialize'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai.rb:12:in `new'
     # /Library/Ruby/Gems/2.0.0/gems/fauxhai-2.3.0/lib/fauxhai.rb:12:in `mock'
     # /Library/Ruby/Gems/2.0.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:373:in `client'
     # /Library/Ruby/Gems/2.0.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:141:in `node'
     # /Library/Ruby/Gems/2.0.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:84:in `initialize'
```
I took a quick look and noticed that the 'windows/2008R2.json' file is specified as UTF-16, while the others are UTF-8.  Converting the file's encoding resolved the issue for me.

If there's any additional information I can provide regarding this issue, let me know.

**Comment by tas50** [comment]
@jrmash Can you commit up the properly encoded file?

**Comment by tas50** [comment]
Merged
